# Generated by Django 3.0.1 on 2020-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='is_en',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', max_length=10),
            preserve_default=False,
        ),
    ]
