# Generated by Django 3.0.1 on 2020-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200112_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='myblog.Tag'),
        ),
    ]
