# Generated by Django 3.0.1 on 2020-01-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200112_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(default='English', on_delete=django.db.models.deletion.CASCADE, to='myblog.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.ForeignKey(default='English', on_delete=django.db.models.deletion.CASCADE, to='myblog.Language'),
            preserve_default=False,
        ),
    ]
