# Generated by Django 3.0.1 on 2020-01-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20200119_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='language',
        ),
    ]
